apiVersion: v1
kind: Service
metadata:
  name: node
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: node